### ISSUE TITLE
Add back functionality to pull owner names

### ISSUE THREAD

**Issue by johnny-papercut** [cwendt94/espn-api#497]
### Sport

Football

### Summary

After updating to 0.33.0, it seems like owners are now represented by their ID and not their human-readable names.

Can owner names be surfaced again?

**Comment by Kjeldgaard** [comment]
You can find inspiration here https://github.com/cwendt94/espn-api/pull/487#issuecomment-1782273387, on how to get owner names.

**Comment by cwendt94** [comment]
Yeah, I will look to adding it back in the new couple days. ESPN had to mess up their data for a little and removed it, but of course now they added it back.

**Comment by joeyagreco** [comment]
Bumping for visibility. Updating to version 0.33.0 broke functionality in a library of mine sadly :/

`AttributeError: 'Team' object has no attribute 'owner'. Did you mean: 'owners'?`

**Comment by cwendt94** [comment]
Owners is back in v0.34.0, format is a little different as they removed owner names in public leagues.

Team.owners will now be an array of dict. It will look like
```
[{ id: '1234', displayName: 'team', firstName: 'Bob', lastName: 'Joe'}]
```
However in public leagues, the name attributes will not be populated.
